### ISSUE TITLE
Implement lemmatisation option

### ISSUE THREAD

**Issue by krisrogers** [Kapiche/caterpillar#46]

**Comment by SamHames** [comment]
I'm thinking about the best way to support this. There's a few places we can consider this:
1. As an indexing time option applied to all terms.
2. As a retrieval time option as a transformation on the retrieved terms - this is interesting for ML type problems where stemming helps reduce dimensionality.
3. As a query time term expansion - for example, allowing lookups for all terms sharing that stem. This could be supported as part of the IndexReader.filter() interface and/or through the get_vocabulary options for finding alternate terms.

I think 3.) is the most useful use case/approach to tackle. 

I'm not a fan of 1.) for analytical work because we're throwing away information straightaway - I'd rather have the option to control this at query time rather than giving it all away at index time. For 2) there are plenty of options outside caterpillar (NLTK, stemming (pure python), pystemmer(wrapper for the snowball project): I don't think by itself this use case really needs to be supported natively.
