### ISSUE TITLE
Change the plugin system

### ISSUE THREAD

**Issue by rstuart85** [Kapiche/caterpillar#57]
Right now, plugins are this kind of adhoc thing that make core modification to an index. For example, if we want to merge word variants before create a topic model, we have to change the underlying index before creating the topic model in a way that con't be undone.

We store the original token information on the frames themselves. This means we could move to a system where model generation can be thought of as a pipeline that can make any mutations it wants before creating and storing the model. It could look something like this:

Apply Mutation(s) -> Generate Model -> Store Model

**Comment by rstuart85** [comment]
This issue is mainly dealing with the API. There are a bunch of other issues to move code out of the index code and into plugins like co-occurrence etc.

**Comment by SamHames** [comment]
Since we need to deal with this now we are running the same plugin over potentially arbitrary combinations of fields in an index, I propose that we change the plugin API to look something like this:

	# 1. initialise a plugin with given parameters
	plugin = ExamplePlugin(reader, fields=['text', 'title'], parameter1=1.2, scaling='log')

	# 2. Run the plugin and return the necessary results needed to regenerate the plugin instance.
	plugin_results = plugin.run()

	# 3. Store the results in the index
	writer.write_plugin_data(plugin_results)

	# 4. Later on, load the plugin from the stored results:
	plugin.load()

In order:
1. the plugin is instantiated with all the parameters needed to run, and can use everything the reader instance provides to work its magic.
2. Actually kicks off the running of the plugin, resulting in a fully functional plugin object, and returning the necessary state to recreate the plugin instance later.
3. Store the plugin results in a plugin data container within the index. The plugin container can be a simple key-value store
4. Recreate the plugin instance later on by loading from the index.

Issues:

- Identifying whether a plugin has been run with a particular set of parameters
- Plugin results need to be serialisable to some standard format (probably start with JSON for simplicity.)
- Key value storage for plugin results might be limiting in terms of performance for things like custom lookup/search options that can't be expressed in terms of searching through the regular reader/searcher interfaces

**Comment by rstuart85** [comment]
My concern with this design is that it requires the model to fit in memory. This is probably not too much of a concern right now but in the longer term, this will be a limiting factor.

**Comment by SamHames** [comment]
Good point - the design case I am thinking here is a plugin that has a moderate amount of internal state that can be easily serialised/deserialised. Will make sure that this is appropriately documented.

Did you have any use cases in mind that would need out of core consideration? Are you thinking of something like a custom index? If we think of this design case as an AnalyticsPlugin, maybe those cases can be covered by an IndexPlugin or other approach to custom indexes.

**Comment by rstuart85** [comment]
Topic calculations require a term co-occurence index. These can be quite large. For a 1 million frame index with a single field, you are looking at almost 1GB in size. Plugin code that requires this and needs to build it across fields probably needs to do it in a streaming fashion. Also, it probably wants to be able to refer back to it and update it as new documents become available. That's the number 1 point for me right now.
